config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'

  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :favorites
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  validates :content_or_picture, presence: true

  mount_uploader :picture, PictureUploader

  def content_or_picture
    content.presence or picture.presence
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:index, :show, :new, :edit]
  before_action :blog_different_user, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.all.order("id DESC")
    @blog = Blog.new
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    @blogs = Blog.all.order("id DESC")
    render :index if @blog.invalid?
  end

  def edit
  end

  def create
    @blogs = Blog.all.order("id DESC")
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :index
    else
      if @blog.save
        PostMailer.post_mail(@blog).deliver
        redirect_to @blog, notice: '投稿しました！'
      else
        render :new
      end
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: '更新しました！'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, alert: '投稿を削除しました！'
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:content, :picture, :picture_cache, :user_id)
  end

  def blog_different_user
    @blog = Blog.find(params[:id])
    if current_user.id != @blog.user_id
      flash[:alert] = "他のユーザーの投稿は編集できません"
      redirect_to blogs_path
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_index_or_edit
    if action_name == 'index' || action_name == 'create' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit' || action_name == 'update'
      blog_path
    end
  end

  def submit_button_value
    if action_name == 'index' || action_name == 'create' || action_name == 'confirm'
      "確認画面へ"
    elsif action_name == 'edit' || action_name == 'update'
      "投稿する"
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, url: choose_index_or_edit ) do |form| %>

  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2>保存中に<%= pluralize(blog.errors.count, "個") %>のエラーが発生しました</h2>
      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="form_table">
    <div class="field">
      <tr>
        <th><%= form.label :picture %></th>
        <%= image_tag(blog.picture.url) if blog.picture && blog.picture.url %>
        <td><%= form.file_field :picture %></td>
        <%= form.hidden_field :picture_cache %>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :content %></th>
        <td><%= form.text_area :content %></td>
      </tr>
    </div>
  </table>
  <div class="actions">
    <%= form.submit submit_button_value %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">
        <div class="box_base">
          <%= form_with(model: @blog, local: true) do |form| %>
            <%= form.hidden_field :picture_cache %>
            <%= form.hidden_field :content %>
            <% if @blog.picture.url && @blog.picture.url %>
              <%= image_tag @blog.picture.url, class: "show_picture" %>
            <% end %>
            <div class="blog_content_box confirm_content_box">
              <p class="blog_content"><%= @blog.content %></p>
            </div>
            <div class="confirm_buttons">
              <%= form.submit  "投稿する", class: 'confirm_submit' %>
              <%= form.submit "戻る", name: 'back', class: 'confirm_back' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/blogs/edit.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">
        <div class="box_base">
          <p class="edit_header">日記を編集する</p>

            <%= render 'form', blog: @blog %>

          <p class="edit_back"><%= link_to '戻る', blogs_path %></p>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/blogs/index.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">

        <div class="modal fade" id="modal1" tabindex="-1"
              role="dialog" aria-labelledby="label1" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="label1">Post your picture</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            <div class="modal-body">
              <%= render 'form', blog: @blog %>
            </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

        <div class="box_base" id="new_button_box_superior">
          <div data-toggle="modal" data-target="#modal1" class="new_button_box" id="new_button_box">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-image" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9c0 .013 0 .027.002.04V12l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094L15 9.499V3.5a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm4.502 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
            </svg>
            <p class="new_button">Post your picture!</p>
          </div>
        </div>

        <% @blogs.each do |blog| %>
          <div class="blog_box box_base">
            <p class="blog_user_name"><%= blog.user.name %><span class="blog_date">   <%= l blog.created_at %></span></p>
            <% if blog.picture.url %>
              <%= image_tag blog.picture.url , class: 'blog_image'%>
            <% end %>
            <div class="blog_content_box">
              <p class="blog_content"><%= blog.content %></p>
            </div>
            <ul class="blog_buttons_box">

              <% unless blog.user_id == current_user.id %>
                <% if current_user.favorites.find_by(blog_id: blog.id).present? %>
                  <li class="blog_buttons">
                    <%= link_to favorite_path(id: current_user.favorites.find_by(blog_id: blog.id).id), method: :delete, class: 'btn btn-fav' do %>
                      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                      </svg>
                    <% end %>
                  </li>
                <% else %>
                  <li class="blog_buttons">
                    <%= link_to favorites_path(blog_id: blog.id), method: :post, class: 'btn btn-fav' do %>
                      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                      </svg>
                    <% end %>
                  </li>
                <% end %>
              <% end %>

              <li class="blog_buttons">
                <%= link_to "詳細", blog_path(blog.id) %>
              </li>
              <% if blog.user_id == current_user.id %>
                <li class="blog_buttons">
                  <%= link_to "編集", edit_blog_path(blog.id) %>
                </li>
                <li class="blog_buttons">
                  <%= link_to '削除', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

<% if @blog.errors.any? || action_name == "create" %>
  <script>
    $('#modal1').modal();
  </script>
<% end %>

app/views/blogs/new.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">
        <div class="box_base">
          <p class="edit_header">投稿を編集する</p>

            <%= render 'form', blog: @blog %>

          <p class="edit_back"><%= link_to '戻る', blogs_path %></p>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/blogs/show.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">
        <div class="box_base">
          <% if @blog.picture.url %>
            <%= image_tag @blog.picture.url, class: "show_picture" %>
          <% end %>
          <% if @blog.content.present? %>
            <div class="blog_content_box confirm_content_box">
              <p class="blog_content"><%= @blog.content %></p>
            </div>
          <% end %>

          <% unless @blog.user_id == current_user.id %>
            <% if @favorite.present? %>
              <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn show_fav_del' %>
            <% else %>
              <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn show_fav' %>
            <% end %>
          <% end %>

          <div class="show_buttons">
            <% if @blog.user_id == current_user.id %>
              <%= link_to '編集', edit_blog_path(@blog), class: "show_edit" %>
            <% end %>
            <%= link_to '戻る', blogs_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>