config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'

  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :favorites
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }

  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  mount_uploader :image, ImageUploader

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog

  #user.active_relationshipsで、自分のidと同じfollower_idが記録されているレコードを取得
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  #user.followingにより、上のアソシエーションを通して、followedのアソシエーションから取得
  has_many :following, through: :active_relationships, source: :followed

  #user.passive_relationshipsで、自分のidと同じfollowed_idが記録されているレコードを取得
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  #user.followersで上のアソシエーションを通して、followerのアソシエーションから取得
  has_many :followers, through: :passive_relationships, source: :follower

  before_validation { email.downcase! }

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :favorites]
  before_action :fobid_login_user, only: [:new, :create]
  before_action :authenticate_user, only: [:show, :edit, :update, :favorites]
  before_action :user_different, only: [:edit, :update, :favorites]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path(@user.id), notice: 'ユーザー登録が完了しました！'
    else
      render :new
    end
  end

  def show
    @following_users = @user.following
    @followers = @user.followers
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: 'ユーザー情報を更新しました！'
    else
      render :edit
    end
  end

  def favorites
    @favorite_blogs = current_user.favorite_blogs.eager_load(:favorites).order("favorites.created_at DESC")
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :image, :image_cache, :password, :password_confirmation)
  end

  def user_different
    @user = User.find(params[:id])
    if current_user.id != @user.id
      flash[:alert] = "他のユーザーの情報は編集できません"
      redirect_to blogs_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_new_or_edit
    if action_name == 'new' || action_name == 'create'
      users_path
    elsif action_name == 'edit' || action_name == 'update'
      user_path
    end
  end

  def user_submit_button_value
    if action_name == 'new' || action_name == 'create'
      "Create your account"
    elsif action_name == "edit" || action_name == 'update'
      "Update your account"
    end
  end
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "つながりを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, url: user_new_or_edit ) do |form| %>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2>登録中に<%= pluralize(user.errors.count, "個") %>のエラーが発生しました</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="form_table" id="user_table">
    <div class="field">
      <tr>
        <th><%= form.label :name %></th>
        <td id="user_name_td"><%= form.text_field :name %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :email %></th>
        <td><%= form.text_field :email %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :image %></th>
        <% if user.image && user.image.url %>
          <%= image_tag user.image.url, class: "edit_img" %>
        <% end %>
        <td><%= form.file_field :image %></td>
        <%= form.hidden_field :image_cache %>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :password %></th>
        <td><%= form.password_field :password %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :password_confirmation %></th>
        <td><%= form.password_field :password_confirmation %></td>
      </tr>
    </div>
  </table>
  <div class="actions" id="user_table_button">
    <%= form.submit user_submit_button_value %>
  </div>
<% end %>

app/views/users/edit.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">
        <div class="user_box_base">

          <% if @user.errors.any? %>
            <br>
          <% end %>
          <%= render 'form', user: @user %>
          <div class="edit_back">
            <%= link_to 'Back', @user %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/favorites.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">

        <% @favorite_blogs.each do |blog| %>
          <div class="blog_box box_base">
            <p class="blog_user_name"><%= blog.user.name %><span class="blog_date">   <%= l blog.created_at %></span></p>
            <% if blog.picture.url %>
              <%= image_tag blog.picture.url , class: 'blog_image'%>
            <% end %>
            <div class="blog_content_box">
              <p class="blog_content"><%= blog.content %></p>
            </div>
            <ul class="blog_buttons_box">

              <% unless blog.user_id == current_user.id %>
                <% if current_user.favorites.find_by(blog_id: blog.id).present? %>
                  <li class="blog_buttons fav_date">登録日 <%= blog.favorites.find_by(user_id: current_user.id).created_at.strftime('%Y/%m/%d %H:%M') %></li>
                  <li class="blog_buttons">
                    <%= link_to favorite_path(id: current_user.favorites.find_by(blog_id: blog.id).id, from: "favorites"), from: "favorites", method: :delete, class: 'btn btn-fav' do %>
                      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                      </svg>
                    <% end %>
                  </li>
                <% else %>
                  <li class="blog_buttons">
                    <%= link_to favorites_path(blog_id: blog.id), method: :post, class: 'btn btn-fav' do %>
                      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                      </svg>
                    <% end %>
                  </li>
                <% end %>
              <% end %>

              <li class="blog_buttons">
                <%= link_to "詳細", blog_path(blog.id) %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">
        <div class="user_box_base">

          <h2 class="user_index_h2">ユーザー</h2>

          <% @users.each do |user| %>
            <% if user.id != current_user.id %>
              <li>
                <div class="item">
                  <%= link_to user.name, user %>
                  <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
                </div>
              </li>
              <li><%= render 'follow_form', user: user %></li> <!-- フォロー機能が実装されて入ればこの一文も必要 -->
            <% end %>
          <% end %>

          <br>


          <table class="user_index_table">
            <% @users.each do |user| %>
              <tr class="user_index_tr">
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= render 'follow_form', user: user %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">
        <div class="user_box_base">

          <h2 class="signup">Sign up!</h2>
          <%= render 'form', user: @user %>

        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main class="container-fluid">
  <div class="container">
    <div class="main_row row">
      <div class="main_wrapper">
        <div class="user_box_base">

          <% if @user.image.thumb.url %>
              <%= image_tag @user.image.thumb.url, class: "user_show_image" %>
          <% end %>

          <div class="name_and_email">
            <p>
              <strong>Name:</strong>
              <%= @user.name %>
            </p>
            <p>
              <strong>Email:</strong>
              <%= @user.email %>
            </p>
          </div>

          <h1>フォロー</h1>
          <table class="user_index_table">
            <% @following_users.each do |user| %>
              <tr class="user_index_tr">
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= render 'follow_form', user: user %></td>
              </tr>
            <% end %>
          </table>

          <h1>フォロワー</h1>
          <table class="user_index_table">
            <% @followers.each do |user| %>
              <tr class="user_index_tr">
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= render 'follow_form', user: user %></td>
              </tr>
            <% end %>
          </table>

          <% if current_user.id == @user.id %>
            <div class="user_show_bottuns">
              <%= link_to edit_user_path(current_user.id) do %>
                <button type="button" class="btn btn-edit">edit</button>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>