config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'

  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get :favorites
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicsNote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default" id="picsnote_header">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/blogs">PicsNote</a>
        </div>
        <div class="collapse navbar-collapse" id="navigation">
          <div class="navbar-text navbar-right">
            <% if logged_in? %>

              <% if current_user.image.url %>
                <%= link_to user_path(current_user.id) do %>
                  <%= image_tag current_user.image.thumb.url, class: "header_user_image" %>
                <% end %>
              <% else %>
                <%= link_to user_path(current_user.id) do %>
                  <button type="button" class="btn btn-default navbar-btn">Profile</button>
                <% end %>
              <% end %>

              <%= link_to favorites_user_path(current_user.id) do %>
                <button type="button" class="btn btn-default navbar-btn">Favorites</button>
              <% end %>
              <%= link_to blogs_path(current_user.id) do %>
                <button type="button" class="btn btn-default navbar-btn">Top</button>
              <% end %>
              <%= link_to session_path(current_user.id), method: :delete do %>
                <button type="button" class="btn btn-default navbar-btn">Logout</button>
              <% end %>
            <% else %>
              <%= link_to new_user_path do %>
                <button type="button" class="btn btn-default navbar-btn">Sign up</button>
              <% end %>
              <%= link_to new_session_path do %>
                <button type="button" class="btn btn-default navbar-btn">Login</button>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <div class="container-fluid">
        <div class="container">
          <div class="main_row row">
            <div class="main_wrapper">

              <% if key == "notice" %>
                <div class="box_base error_box error_notice">
                  <div class="error_message_box">
                    <%= content_tag(:div, value, class: "#{key}") %>
                  </div>
                </div>
              <% elsif key == "alert" %>
                <div class="box_base error_box error_alert">
                  <div class="error_message_box">
                    <%= content_tag(:div, value, class: "#{key}") %>
                  </div>
                </div>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>